<?php

use Illuminate\Database\Schema\Blueprint;

/**
 * Updater to add bool value indicating auto generated management
 *
 * @author Patrick Reichel
 */
class UpdatePhonenumberManagementForAutogenerateMarker extends BaseMigration
{
    // name of the table to create
    protected $tablename = 'phonenumbermanagement';

    /**
     * Run the migrations.
     * On importing existing EnviaOrders we possibly have to auto-generate managements.
     * As this managements probably needs manual interaction we add a marker column…
     *
     * @return void
     */
    public function up()
    {
        Schema::table($this->tablename, function (Blueprint $table) {
            $table->boolean('autogenerated')->default(0);
        });

        $this->set_fim_fields([
            'subscriber_company',
            'subscriber_department',
            'subscriber_firstname',
            'subscriber_lastname',
            'subscriber_street',
            'subscriber_house_number',
            'subscriber_zip',
            'subscriber_city',
            'subscriber_district',
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table($this->tablename, function (Blueprint $table) {
            $table->dropColumn('autogenerated');
        });

        $this->set_fim_fields([
            'subscriber_company',
            'subscriber_firstname',
            'subscriber_lastname',
            'subscriber_street',
            'subscriber_house_number',
            'subscriber_zip',
            'subscriber_city',
            'subscriber_district',
        ]);
    }
}
